steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/hive-mind-repo/hive-mind-frontend:$SHORT_SHA',
      '--build-arg', 'VITE_API_BASE_URL=$_VITE_API_BASE_URL',
      '--build-arg', 'VITE_SUPABASE_URL=$_VITE_SUPABASE_URL',
      '--build-arg', 'VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY',
      '.'
    ]
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/hive-mind-repo/hive-mind-frontend:$SHORT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'hive-mind-frontend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/hive-mind-repo/hive-mind-frontend:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'
    ]
