apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hive-mind-bot
spec:
  template:
    spec:
      containers:
      - image: gcr.io/${PROJECT_ID}/hive-mind-bot
        ports:
        - containerPort: 3000
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: GOOGLE_REDIRECT_URI
        - name: BOT_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: BOT_REFRESH_TOKEN
        - name: BOT_EMAIL
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: BOT_EMAIL
        - name: BOT_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hive-mind-secrets
              key: BOT_EMAIL_PASSWORD
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi" 